[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[form]]
  name = "contact"

[[form]]
  name = "booking"
  
[[notifications]]
  form = "contact"
  email = "murraykeira@yahoo.com"

[[notifications]]
  form = "booking"
  email = "murraykeira@yahoo.com"
